name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push frontend to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Add Hugging Face remote
          git remote add frontend-hf https://Vinay8903:$HF_TOKEN@huggingface.co/spaces/Vinay8903/Rag-chat-frontend || true
          
          # Fetch latest changes
          git fetch frontend-hf main

          # Pull remote changes into subtree split (merge if needed)
          git subtree pull --prefix=frontend frontend-hf main --squash || true

          # Push to Hugging Face space
          git subtree push --prefix=frontend frontend-hf main || \
          git push --force frontend-hf $(git subtree split --prefix=frontend):main
  sync-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false
      
      - name: Push backend to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git subtree push --prefix=backend https://Vinay8903:$HF_TOKEN@huggingface.co/spaces/Vinay8903/Rag-chat-backend main || \
          git push --force https://Vinay8903:$HF_TOKEN@huggingface.co/spaces/Vinay8903/Rag-chat-backend $(git subtree split --prefix=backend):main